
enum Asset {
  USDG,
  SPY,
}

"""
String that represents a string that contains a percentage amount that's safe to display
in the UI.
"""
scalar Percent

"""
Amount in circulation in the system, 18 decimals. Returned as a string.
"""
scalar Amount

"""
Bytes32 that we use behind the scenes.
"""
scalar Bytes32

"""
Address on Robinhood Testnet.
"""
scalar Address

"""
EVM hash that we return here.
"""
scalar Hash

type Collateral {
  name: String!,
}

"""
Borrow details in circulation.
"""
type BorrowDetails {
  collateral: Collateral!,
  avgRatePa: Percent!,
  deposited: Amount!,
  debtIssued: Amount!
}

"""
An open Florin borrowing position owned by an address.
"""
type Position {
  troveId: String!,
  troveManager: Address!,
  owner: Address!,
  debt: Amount!,
  collateral: Amount!,
  stake: Amount!,
  annualInterestRate: Percent!,
  interestBatchManager: Address
}

"""
Earn rewards that we display in the UI.
"""
type EarnRewards {
  collateral: Collateral!,
  apr: Percent!,
  poolSize: Amount!,
  coverage: Percent!
}

input Permit {
  deadline: Int!,
  permitV: Int!,
  permitR: String!,
  permitS: String!
}

type Query {
  """
  Details of the borrowed amount of SPY in circulation with FUSD.
  """
  borrowDetails: [BorrowDetails!],

  """
  Earn rewards details.
  """
  earnRewards: [EarnRewards!]!

  """
  Open positions for a specific address given.
  """
  openPositions(owner: Address!): [Position!]!
}

type CreateAccountExec {
  hash: Hash!,
  secret: String!
}

type FlorinOpenPositionResult {
  hash: Hash!
}

"""
Input to create an account, with an Authority set by the server.
"""
input CreateAccount {
  eoa_addr: Address!,
  sigV: Int!,
  sigR: Bytes32!,
  sigS: Bytes32!
}

input FlorinOpenPosition {
  owner: Address!,
  """
  The asset to start the open position interaction from. At first, this will convert using
  Uniswap V4.
  """
  asset: Asset!,
  collateralAmt: Amount!,
  boldAmt: Amount!,
  annualInterestRate: Amount!,
  ownerIndex: Amount!,
  maxUpfrontFee: Amount!,
  lowerHint: Amount!,
  upperHint: Amount!,
  addManager: Address,
  removeManager: Address,
  receiver: Address!,
  permit: Permit
}

type Mutation {
  """
  Open a position using Florin, while creating an account.
  """
  createAccountFlorinOpenPosition(
    createAccount: CreateAccount!,
    openPosition: FlorinOpenPosition!,
    gasToken: Asset!,
    gasTokenAmt: String!,
    dryrun: Boolean
  ): CreateAccountExec

  """
  Open a position using Florin.
  """
  florinOpenPosition(openPosition: FlorinOpenPosition!): FlorinOpenPositionResult
}
